# Generated by Django 2.0.6 on 2018-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180615_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_video_url',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
