# Generated by Django 2.0.6 on 2018-06-16 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0006_auto_20180616_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='owner',
            field=models.ForeignKey(default='8', on_delete=django.db.models.deletion.CASCADE, related_name='newpost', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
